version: '3.8'

services:
  apigateway:
    build: ./totos-apigateway/apigateway/
    container_name: apigateway
    depends_on:
      - mysql
  authapi:
      build: ./totos-authAPI/auth-api/
      container_name: authapi
      environment:
        - DB_URL=jdbc:mysql://mysql:3306/usersdb
        - DB_USERNAME=root
        - DB_PASSWORD=1258963abc
      depends_on:
        - mysql
        - apigateway
  productsapi:
    build: ./totos-productsAPI/productsAPI/
    container_name: productsapi
    environment:
      - DB_URL=jdbc:mysql://mysql:3306/productsdb
      - DB_USERNAME=root
      - DB_PASSWORD=1258963abc
    depends_on:
      - mysql
      - apigateway
  usersapi:
    build: ./totos-usersAPI/usersAPI/
    container_name: usersapi
    depends_on:
      - mysql
      - apigateway
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_DATABASE: usersdb
      MYSQL_ROOT_PASSWORD: 1258963abc
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db_data: