version: '3.8'

services:
  apigateway:
    build: ./totos-apigateway/apigateway/
    container_name: apigateway
    environment:
      - DB_URL=mysql://mysql:3306/usersdb
      - DB_USERNAME=root
      - DB_PASSWORD=1258963abc
    depends_on:
      - mysql
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_DATABASE: usersdb
      MYSQL_ROOT_PASSWORD: 1258963abc
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db_data: